-- Disable Row Level Security on all tables
ALTER TABLE tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE agents DISABLE ROW LEVEL SECURITY;
ALTER TABLE approvals DISABLE ROW LEVEL SECURITY;
ALTER TABLE outputs DISABLE ROW LEVEL SECURITY;
ALTER TABLE activity_events DISABLE ROW LEVEL SECURITY;
